//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_LoginForm.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Shop.
        /// </summary>
        public static string ActivityBtn {
            get {
                return ResourceManager.GetString("ActivityBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Admin Settings.
        /// </summary>
        public static string AdminBtn {
            get {
                return ResourceManager.GetString("AdminBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Albums.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Albums.
        /// </summary>
        public static string AlbumsBtn {
            get {
                return ResourceManager.GetString("AlbumsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Artists.
        /// </summary>
        public static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Artists.
        /// </summary>
        public static string ArtistsBtn {
            get {
                return ResourceManager.GetString("ArtistsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Promote.
        /// </summary>
        public static string Awans {
            get {
                return ResourceManager.GetString("Awans", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Promote to Admin.
        /// </summary>
        public static string AwansujNaAdmina {
            get {
                return ResourceManager.GetString("AwansujNaAdmina", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bag.
        /// </summary>
        public static string Bag {
            get {
                return ResourceManager.GetString("Bag", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Browce.
        /// </summary>
        public static string BrowceBtn {
            get {
                return ResourceManager.GetString("BrowceBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kup.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change Background:.
        /// </summary>
        public static string ChangeBackground {
            get {
                return ResourceManager.GetString("ChangeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change Buttons:.
        /// </summary>
        public static string ChangeButtons {
            get {
                return ResourceManager.GetString("ChangeButtons", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change Language:.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dark.
        /// </summary>
        public static string Ciemne {
            get {
                return ResourceManager.GetString("Ciemne", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add.
        /// </summary>
        public static string Dodaj {
            get {
                return ResourceManager.GetString("Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Song.
        /// </summary>
        public static string DodajMuzyke {
            get {
                return ResourceManager.GetString("DodajMuzyke", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light.
        /// </summary>
        public static string Jasne {
            get {
                return ResourceManager.GetString("Jasne", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Main:.
        /// </summary>
        public static string MainBlock {
            get {
                return ResourceManager.GetString("MainBlock", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Studio Name:.
        /// </summary>
        public static string NowaNazwa {
            get {
                return ResourceManager.GetString("NowaNazwa", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Current Studio Name:.
        /// </summary>
        public static string ObecnaNazwaStudia {
            get {
                return ResourceManager.GetString("ObecnaNazwaStudia", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Current Logo.
        /// </summary>
        public static string ObecneLogo {
            get {
                return ResourceManager.GetString("ObecneLogo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Polish.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search:.
        /// </summary>
        public static string SearchBox {
            get {
                return ResourceManager.GetString("SearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        public static string SettingsBtn {
            get {
                return ResourceManager.GetString("SettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Songs.
        /// </summary>
        public static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Songs.
        /// </summary>
        public static string SongsBtn {
            get {
                return ResourceManager.GetString("SongsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Style 1.
        /// </summary>
        public static string Styl1 {
            get {
                return ResourceManager.GetString("Styl1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Style 2.
        /// </summary>
        public static string Styl2 {
            get {
                return ResourceManager.GetString("Styl2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Admin Nick:.
        /// </summary>
        public static string txtUser {
            get {
                return ResourceManager.GetString("txtUser", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Resign.
        /// </summary>
        public static string txtUser1 {
            get {
                return ResourceManager.GetString("txtUser1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        public static string Usun {
            get {
                return ResourceManager.GetString("Usun", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete Song.
        /// </summary>
        public static string UsunMuzyke {
            get {
                return ResourceManager.GetString("UsunMuzyke", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu View Terms and Conditions:.
        /// </summary>
        public static string ViewTermsAndConditions {
            get {
                return ResourceManager.GetString("ViewTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Welcome to the Store!.
        /// </summary>
        public static string WelcomeToTheStrore {
            get {
                return ResourceManager.GetString("WelcomeToTheStrore", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Album Name:.
        /// </summary>
        public static string WpiszAlbum {
            get {
                return ResourceManager.GetString("WpiszAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Song Name:.
        /// </summary>
        public static string WpiszNazweUtworu {
            get {
                return ResourceManager.GetString("WpiszNazweUtworu", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Artist Name:.
        /// </summary>
        public static string WpiszWykonawce {
            get {
                return ResourceManager.GetString("WpiszWykonawce", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select.
        /// </summary>
        public static string Wybierz {
            get {
                return ResourceManager.GetString("Wybierz", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select Image.
        /// </summary>
        public static string WybierzZdjecie {
            get {
                return ResourceManager.GetString("WybierzZdjecie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your music:.
        /// </summary>
        public static string YourMusicBlock {
            get {
                return ResourceManager.GetString("YourMusicBlock", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change.
        /// </summary>
        public static string Zmien {
            get {
                return ResourceManager.GetString("Zmien", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change Logo.
        /// </summary>
        public static string ZmienLogo {
            get {
                return ResourceManager.GetString("ZmienLogo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change Logo.
        /// </summary>
        public static string ZmienLogoAplikacji {
            get {
                return ResourceManager.GetString("ZmienLogoAplikacji", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change Song.
        /// </summary>
        public static string ZmienMuzyke {
            get {
                return ResourceManager.GetString("ZmienMuzyke", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change Studio Name.
        /// </summary>
        public static string ZmienNazweStudia {
            get {
                return ResourceManager.GetString("ZmienNazweStudia", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Resign Admin.
        /// </summary>
        public static string ZrzeknijSieAdmina {
            get {
                return ResourceManager.GetString("ZrzeknijSieAdmina", resourceCulture);
            }
        }
    }
}
