//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_LoginForm.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string ActivityBtn {
            get {
                return ResourceManager.GetString("ActivityBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Settings.
        /// </summary>
        public static string AdminBtn {
            get {
                return ResourceManager.GetString("AdminBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string AlbumsBtn {
            get {
                return ResourceManager.GetString("AlbumsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string ArtistsBtn {
            get {
                return ResourceManager.GetString("ArtistsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote.
        /// </summary>
        public static string Awans {
            get {
                return ResourceManager.GetString("Awans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote to Admin.
        /// </summary>
        public static string AwansujNaAdmina {
            get {
                return ResourceManager.GetString("AwansujNaAdmina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag.
        /// </summary>
        public static string Bag {
            get {
                return ResourceManager.GetString("Bag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseBtn {
            get {
                return ResourceManager.GetString("BrowseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kup.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Background:.
        /// </summary>
        public static string ChangeBackground {
            get {
                return ResourceManager.GetString("ChangeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Buttons:.
        /// </summary>
        public static string ChangeButtons {
            get {
                return ResourceManager.GetString("ChangeButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language:.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Ciemne {
            get {
                return ResourceManager.GetString("Ciemne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Dodaj {
            get {
                return ResourceManager.GetString("Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Song.
        /// </summary>
        public static string DodajMuzyke {
            get {
                return ResourceManager.GetString("DodajMuzyke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Jasne {
            get {
                return ResourceManager.GetString("Jasne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main:.
        /// </summary>
        public static string MainBlock {
            get {
                return ResourceManager.GetString("MainBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Studio Name:.
        /// </summary>
        public static string NowaNazwa {
            get {
                return ResourceManager.GetString("NowaNazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Studio Name:.
        /// </summary>
        public static string ObecnaNazwaStudia {
            get {
                return ResourceManager.GetString("ObecnaNazwaStudia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Logo.
        /// </summary>
        public static string ObecneLogo {
            get {
                return ResourceManager.GetString("ObecneLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string SearchBox {
            get {
                return ResourceManager.GetString("SearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsBtn {
            get {
                return ResourceManager.GetString("SettingsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string SongsBtn {
            get {
                return ResourceManager.GetString("SongsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 1.
        /// </summary>
        public static string Styl1 {
            get {
                return ResourceManager.GetString("Styl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style 2.
        /// </summary>
        public static string Styl2 {
            get {
                return ResourceManager.GetString("Styl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Admin Nick:.
        /// </summary>
        public static string txtUser {
            get {
                return ResourceManager.GetString("txtUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resign.
        /// </summary>
        public static string txtUser1 {
            get {
                return ResourceManager.GetString("txtUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Usun {
            get {
                return ResourceManager.GetString("Usun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Song.
        /// </summary>
        public static string UsunMuzyke {
            get {
                return ResourceManager.GetString("UsunMuzyke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Terms and Conditions:.
        /// </summary>
        public static string ViewTermsAndConditions {
            get {
                return ResourceManager.GetString("ViewTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Store!.
        /// </summary>
        public static string WelcomeToTheStrore {
            get {
                return ResourceManager.GetString("WelcomeToTheStrore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Name:.
        /// </summary>
        public static string WpiszAlbum {
            get {
                return ResourceManager.GetString("WpiszAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Name:.
        /// </summary>
        public static string WpiszNazweUtworu {
            get {
                return ResourceManager.GetString("WpiszNazweUtworu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist Name:.
        /// </summary>
        public static string WpiszWykonawce {
            get {
                return ResourceManager.GetString("WpiszWykonawce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Wybierz {
            get {
                return ResourceManager.GetString("Wybierz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string WybierzZdjecie {
            get {
                return ResourceManager.GetString("WybierzZdjecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your music:.
        /// </summary>
        public static string YourMusicBlock {
            get {
                return ResourceManager.GetString("YourMusicBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Zmien {
            get {
                return ResourceManager.GetString("Zmien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Logo.
        /// </summary>
        public static string ZmienLogo {
            get {
                return ResourceManager.GetString("ZmienLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Logo.
        /// </summary>
        public static string ZmienLogoAplikacji {
            get {
                return ResourceManager.GetString("ZmienLogoAplikacji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Song.
        /// </summary>
        public static string ZmienMuzyke {
            get {
                return ResourceManager.GetString("ZmienMuzyke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Studio Name.
        /// </summary>
        public static string ZmienNazweStudia {
            get {
                return ResourceManager.GetString("ZmienNazweStudia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resign Admin.
        /// </summary>
        public static string ZrzeknijSieAdmina {
            get {
                return ResourceManager.GetString("ZrzeknijSieAdmina", resourceCulture);
            }
        }
    }
}
